### PR TITLE
 Add C and Cpp file icons

### PR DESCRIPTION
**Pull request by aveepsit**
- Adds icon to .c, .h files as c
- Adds icon to .cpp, .cxx, .hpp, .hxx as cpp (c++)

### CODE REVIEW

**Comment by aveepsit** [comment]
I have tried to add support for C and C++ file types.

**Comment by aveepsit** [comment]
@donovanhiland

**Comment by donovanhiland** [comment]
Thanks! Sorry I haven't been around to merge this. Would you be willing to add some files to the examples directory to show what files extensions will have which icons? Will keep an eye on this to merge asap

**Comment by aveepsit** [comment]
I have already added two files for the same in the example directory :) 
1) c-file.c
2) c-plus-plus-file.cpp

**Comment by donovanhiland** [comment]
Oops I missed that. Thank you

**Pull request merged**
